version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: lldb
    restart: always
    environment:
      MYSQL_DATABASE: lldb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"   # Host port 3307 -> Container port 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: sdpbackend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8081
    depends_on:
      - db
    ports:
      - "2004:8081"   # Host port 2004 -> container 8081
    networks:
      - ecommerce-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

volumes:
  db_data:

networks:
  ecommerce-net:
    driver: bridge
